# Generated by Django 5.2.4 on 2025-08-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='article',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
