# Generated by Django 5.2.4 on 2025-08-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recap', '0002_activite_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='is_echange_payant',
            field=models.BooleanField(default=False),
        ),
    ]
