# Generated by Django 5.2.4 on 2025-08-09 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recap', '0003_activite_is_echange_payant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recapmensuel',
            unique_together={('partenaire', 'mois')},
        ),
    ]
